default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>

development:
  primary:
    <<: *default
    database: bifrost_development
  cache:
    <<: *default
    database: bifrost_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: bifrost_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: bifrost_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: bifrost_test
  cache:
    <<: *default
    database: bifrost_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: bifrost_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: bifrost_test_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: bifrost_production
  cache:
    <<: *default
    database: bifrost_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: bifrost_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: bifrost_production_cable
    migrations_paths: db/cable_migrate
